name: Release

on:
  release:
    types: [created]

permissions: {}

env:
  GOPRIVATE: github.com/strait-dev/*

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Configure access to private strait-go module
        env:
          SDK_ACCESS_TOKEN: ${{ secrets.SDK_ACCESS_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${SDK_ACCESS_TOKEN}@github.com/strait-dev/".insteadOf "https://github.com/strait-dev/"

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
